### ISSUE TITLE
What is the source of 'hyperA' and 'rsexpm'?

### ISSUE THREAD

**Issue by richelbilderbeek** [Giappo/mbd#3]
@Giappo : `mbd` uses the packages 'hyperA' and 'rsexpm'. These are not CRAN packages. Where did you get these from?

**Comment by Giappo** [comment]
Hi Richel,

This is Hanno's wizardry.

**Comment by richelbilderbeek** [comment]
Where can I download Hanno's wizardry?
Or: could you upload it somewhere?

**Comment by richelbilderbeek** [comment]
Ah, they are in the `libs` folder!
