### ISSUE TITLE
Likelihood PMB and MBD should match for zero extinction

### ISSUE THREAD

**Issue by richelbilderbeek** [Giappo/mbd#6]
(note to self: PMB = Pure Multiple Birth)

Add this as a test...

**Comment by richelbilderbeek** [comment]
I leave this up to Giovanni to maybe do this. If he thinks this is unimportant, this Issue can be closed.

**Comment by Giappo** [comment]
Nah, this is incorrect @richelbilderbeek :grin:

Will close this Issue :+1:
